context_length: 336
dataset: uber_tlc_hourly
diffusion_config: diffusion_small_config
init_skip: false
prediction_length: 24
scaling_type: mean
use_features: false
use_lags: true
lr_scale: 
  deepar: 2.0
  transformer: 2.0
epoch_alpha: 
  deepar: 1
  transformer: 1
num_samples: 10000
scaling_type:
  linear: mean
  deepar: mean
  transformer: mean