base_model: linear
context_length: 312
dataset: m4_hourly
diffusion_config: diffusion_small_config
init_skip: false
iterations: 20
num_samples: 100
prediction_length: 48
refiner_configs:
- guidance: MSE
  lr: 0.01
  refiner_name: most_likely
- guidance: quantile
  lr: 0.01
  refiner_name: most_likely
- guidance: MSE
  method: lmc
  method_kwargs:
    noise_scale: 0.1
  refiner_name: mcmc
  step_size: 0.01
- guidance: quantile
  method: lmc
  method_kwargs:
    noise_scale: 0.1
  refiner_name: mcmc
  step_size: 0.01
use_features: false
use_lags: false
