config:
  batch_size: 64
  beta_ratio: 1
  config: configs/train_tsdiff/train_wiki.yaml
  context_length: 360
  dataset: wiki2000_nips
  device: cuda:6
  diffusion_config: diffusion_small_config
  eval_every: 100
  freq: 1D
  gradient_clip_val: 0.5
  init_skip: false
  is_train: 0
  lr: 0.001
  max_epochs: 1000
  missing_data_configs:
  - missing_scenario: none
    missing_values: 0
  model: unconditional
  normalization: mean
  num_batches_per_epoch: 128
  num_samples: 4
  out_dir: ./results/
  prediction_length: 30
  sampler: ddpm
  sampler_params:
    guidance: quantile
    scale: 8.0
  schedule: cosine
  seed: 1
  setup: forecasting
  tau: 2.0
  test_miss: 0
  test_scale: 8.0
  time_embed: 0
  timesteps: 100
  train_scale:
  - '999'
  use_features: false
  use_lags: false
  use_validation_set: true
metrics:
- ND: 0.2332858221823655
  NRMSE: 2.0332595549832067
  mean_wQuantileLoss: 0.2094451737503934
  missing_scenario: none
  missing_values: 0
version: 1
